services:
  - type: web
    name: satvic-api
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ZOHO_CLIENT_ID
        sync: false
      - key: ZOHO_CLIENT_SECRET
        sync: false
      - key: ZOHO_REFRESH_TOKEN
        sync: false
      - key: ZOHO_ACCOUNT_ID
        sync: false
      - key: ZOHO_MAIL_FROM
        value: noreply@satvictaste.com
      - key: SUPPORT_EMAIL
        value: support@satvictaste.com

